---
title: "Strava API Practice"
author: "Shannon Carter"
date: "10/11/2021"
output: 
  html_document:
    toc: true
    toc_float: true
    theme: united
    highlight: tango 
---

## Packages
```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = FALSE)
knitr::opts_chunk$set(warning = FALSE)
knitr::opts_chunk$set(message = FALSE)

# devtools::install_github("bldavies/stravadata")
# devtools::install_github("marcusvolz/strava")
library(stravadata)
library(yaml)
library(httr)
library(jsonlite)
library(tidyverse)
library(highcharter)
library(lubridate)
library(janitor)
library(here)
library(forcats)
source("https://raw.githubusercontent.com/iascchen/VisHealth/master/R/calendarHeat.R")
```

## Plot Themes
```{r }
strava_hc = hc_theme_merge(
  hc_theme_smpl(),
  hc_theme(colors = c("#ffffff", "#C6C6C6"),
    marker = list(fillColor = c("#ffffff", "#f26852", "#2a366c", "#3ead92", "#5f6fc1", "#f9cd21"), 
                         lineColor = "#000", radius = 3, lineWidth = 1, symbol = "circle"), 
           chart = list(backgroundColor = "#fc4c02", 
                        style = list(fontFamily = "Montserrat", fontSize = "28px", 
                                     color="#fff",fontWeight="500")),
           title = list(style = list(fontFamily = "Montserrat", 
                                     fontWeight = "bold",
                                     color="white"),
                        align = "left"), 
           subtitle = list(style = list(fontFamily = "Montserrat", 
                                        color="#fff",
                                        textTransform="initial",
                                        fontWeight="400",
                                        fontSize = "14px"),
                           align = "left"), 
           legend = list(align = "right", 
                         style = list(fontFamily = "Montserrat", color="white"),
                         itemStyle = list(fontFamily = 'Montserrat', color = 'white'),
                         itemHoverStyle = list(color = 'gray'),   
                         verticalAlign = "top"),
           credits = list(style = list(color = "#fff")),
           caption = list(style = list(color = "fff", 
                                       fontSize = "12px",
                                       fontWeight = "500"),
                          x = 15),
           xAxis = list(labels =list(style = list(fontFamily = "Montserrat", color="#fff")), 
                        title = list(style = list(color = "#fff", fontSize = "15px", 
                                                  color="#fff",fontWeight="500")),
                        gridLineWidth = 0.7,
                        gridLineColor = 'rgba(243,243,243,0.15)', 
                        lineColor = 'rgba(255,255,255,0.7)', 
                        minorGridLineColor = 'rgba(243,243,243,0.7)', 
                        tickColor = "#F3F3F3", 
                        tickWidth = 2), 
           yAxis = list(labels =list(style = list(fontFamily = "Montserrat", color="#fff")), 
                        title = list(style = list(color = "#fff", fontSize = "15px", 
                                                  color="#fff",fontWeight="500")), 
                        gridLineWidth = .7,
                        gridLineColor = 'rgba(243,243,243,0.15)', 
                        lineColor = 'rgba(255,255,255,0.15)', 
                        minorGridLineColor = 'rgba(243,243,243,0.15)', 
                        tickColor = "#F3F3F3", 
                        tickWidth = 2)))

strava_gg = function (base_size = 14,
                     base_family = "Montserrat",
                     title_size = 23,
                     subtitle_size = 12,
                     caption_size = 10,
                     ...)
{
  ggplot2::theme_minimal(base_size = base_size, base_family = base_family, ...) +
    ggplot2::theme(
      plot.title = ggtext::element_markdown(
        size = title_size,
        color = "#ffffff",
        family = "Montserrat-ExtraBold"
      ),
      plot.subtitle = ggtext::element_markdown(size = subtitle_size,
                                               color = "white",
                                               family = "Montserrat"),
      plot.caption = ggplot2::element_text(
        family = "Montserrat-Regular",
        color = "#ffffff",
        size = caption_size,
        lineheight = 1,
        hjust = 0,
        vjust = -5
      ),
      axis.title.x = ggplot2::element_text(
        family = "Montserrat-Bold",
        size = 8,
        color = "#ffffff"
      ),
      axis.title.y = ggplot2::element_text(
        family = "Montserrat-Bold",
        size = 8,
        color = "#ffffff"
      ),
      legend.position = "none",
      plot.margin = ggplot2::unit(c(
        t = 1,
        r = 1.5,
        b = 2,
        l = 1
      ), "lines")
    ) +
    ggplot2::theme(
      plot.background = element_rect(fill = "#fc4c02"),
      axis.line.x = ggplot2::element_line(color = "#ffffff", size = 0),
      panel.background = element_rect(fill = "#fc4c02", color = "transparent"), # bg of the panel
      panel.grid.major.y = ggplot2::element_line(color = "#ffffff", size = 0.2),
      panel.grid.minor.y = ggplot2::element_blank(),
      panel.grid.major.x = ggplot2::element_line(color = "#ffffff", size = 0.2),
      panel.grid.minor.x = ggplot2::element_blank(),
      axis.title.x = ggplot2::element_text(hjust = 1, color = "#ffffff"),
      axis.title.y = ggplot2::element_text(hjust = 1, color = "#ffffff"),
      axis.text = ggplot2::element_text(color = "#ffffff"),
      axis.ticks = ggplot2::element_line(size = 0.6, color = "#ffffff"),
      #panel.border = ggplot2::element_rect(color = "#ffffff", size = 0.8)
    )
}
```


## Setup and Authentication
```{r, eval = F}
# https://bldavies.com/blog/accessing-strava-api/
credentials = read_yaml("credentials.yml")
app = oauth_app("strava", credentials$client_id, credentials$secret)
endpoint = oauth_endpoint(
  request = NULL,
  authorize = "https://www.strava.com/oauth/authorize",
  access = "https://www.strava.com/oauth/token"
)

token = oauth2.0_token(endpoint, app, as_header = FALSE,
                        scope = "activity:read_all")

```


## Extract Data
```{r, eval = F}
df_list = list()
i = 1
done = FALSE
while (!done) {
  req = GET(
    url = "https://www.strava.com/api/v3/athlete/activities",
    config = token,
    query = list(per_page = 200, page = i)
  )
  df_list[[i]] = fromJSON(content(req, as = "text"), flatten = TRUE)
  if (length(content(req)) < 200) {
    done = TRUE
  } else {
    i = i + 1
  }
}

df = rbind_pages(df_list)
write_rds(df, here::here("clean-data", "shannon_strava_raw.rds"))
```

## Clean Data
```{r}
df = read_rds(here::here("clean-data", "shannon_strava_raw.rds"))

strava = df %>% 
  select(name, distance, moving_time, elapsed_time, total_elevation_gain,
         type, workout_type, start_date_local, 
         achievement_count, kudos_count, photo_count, athlete_count,
         average_heartrate, max_heartrate, total_photo_count, suffer_score, 
         map.summary_polyline) %>% 
  mutate(date = as.Date(start_date_local)) %>% 
  mutate(distance = round(distance/1609, 1),
         moving_time = round(moving_time / 60, 1))


```

## Plots
```{r}
strava %>% 
  count(type) %>% 
  ggplot(aes(y = reorder(type, n), x = n)) + 
  geom_bar(stat = "identity", fill = "white") + 
  strava_gg() +
  labs(x = "number of activities", y = NULL)

```

```{r}
strava %>% 
  filter(type %in% c("Ride", "Run", "Swim")) %>% 
  ggplot(aes(x = type, y = kudos_count)) + 
  geom_violin(color = "white") +
  strava_gg() +
  labs(x = NULL, y = "number of kudos earned")

```

```{r}
strava %>% 
  filter(type %in% c("Ride", "Run", "Swim")) %>% 
  ggplot(aes(x = type, y = distance)) + 
  geom_boxplot(outlier.color = "#ffffff", color = "white", fill = "#d3d3d3") +
  strava_gg() +
  labs(x = NULL, y = "distance (mi)")
```

```{r}
strava %>% 
  hchart("scatter", hcaes(x = total_photo_count, y = kudos_count, size = distance)) %>% 
  hc_tooltip(formatter = JS("function(){
                                return (this.point.name + 
                            ' <br> Sport: ' + this.point.type +
                                      ' <br> Kudos Received: ' + this.y + 
                                      ' <br> Number of photos uploaded: ' + this.x +
                                      ' <br> Distance: ' + this.point.distance)}")) %>%
  hc_xAxis(title = list(text = "Number of photos uploaded")) %>% 
  hc_yAxis(title = list(text = "Kudos Received")) %>%
  hc_add_theme(strava_hc) %>% 
  hc_title(text = "picture perfect")

strava %>% 
  filter(kudos_count > 0) %>% 
  ggplot(aes(x = total_photo_count, y = kudos_count, size = distance)) +
  geom_jitter(color = "white", alpha = 0.3) +
  strava_gg() +
  geom_smooth(color = "#d3d3d3", fill = "#d3d3d3", method = "lm") +
  labs(x = "number of photos", 
       y = "number of kudos",
       subtitle = "Each photo on an activity is worth on average 2.5 kudos (p < 0.0001)") 

m1 = lm(kudos_count ~ total_photo_count + distance, data = strava)
summary(m1)
```
# Kudos model
```{r}
library(tidymodels)
library(readr)
library(broom.mixed)
library(dotwhisker)


running = strava %>% 
  filter(type == "Run") %>% 
  # for blog and most analyses, only interested in complete years
  #filter(date > "2017-12-31" & date < "2022-01-01") %>% 
  mutate(min_per_mile = moving_time / distance) %>% 
  mutate(week = floor_date(date, "week"),
         year = year(date),
         month = floor_date(date, "month"),
         year = as.factor(year(date)),
         doy = yday(date),
         dow = wday(date, label = T, abbr = T)) %>% 
  # convert distance from m to mi, time from seconds to minutes
  mutate(distance = round(distance/1609.34, 1),
         moving_time = moving_time / 60,
         year = as.numeric(year)) %>% 
  mutate(half_marathon = case_when(workout_type == 1 & distance > 12 & distance < 15 ~ "y",
                                   T ~ "n"),
         emojis = str_detect(name, "[^[:ascii:]]") == T,
         race = case_when(workout_type == 1 ~ TRUE,
                          T ~ F)) %>% 
  select(name, emojis,
         date, doy, dow, week, month, year,  
         moving_time, distance, min_per_mile, total_elevation_gain, race, athlete_count,
         achievement_count, kudos_count, total_photo_count, 
         average_heartrate, max_heartrate, suffer_score, half_marathon)

options(scipen = 100)
  
lm_fit <- linear_reg() %>% 
  set_engine("lm") %>% 
  fit(kudos_count ~ distance + total_photo_count + year + min_per_mile + achievement_count + suffer_score + emojis + race + athlete_count, data = running)
lm_fit
View(tidy(lm_fit))

tidy(lm_fit) %>% 
  dwplot(dot_args = list(size = 2, color = "black"),
         whisker_args = list(color = "black"),
         vline = geom_vline(xintercept = 0, colour = "grey50", linetype = 2))

ggplot(running, aes(x = distance, y = kudos_count, color = dow)) + geom_point() +
  geom_smooth(method = "lm", se = F)

m2 = lm(kudos_count ~ dow + distance + min_per_mile + achievement_count + total_photo_count + suffer_score, data = running)
summary(m2)
```

```{r}
strava %>% 
  hchart("scatter", hcaes(x = suffer_score, y = kudos_count, size = distance)) %>% 
  hc_tooltip(formatter = JS("function(){
                                return (this.point.name + 
                            ' <br> Sport: ' + this.point.type +
                                      ' <br> Kudos Received: ' + this.y + 
                                      ' <br> Suffer Score: ' + this.x +
                                      ' <br> Distance: ' + this.point.distance)}")) %>%
  hc_xAxis(title = list(text = "Suffer Score")) %>% 
  hc_yAxis(title = list(text = "Kudos Received")) %>%
  hc_add_theme(strava_hc) %>% 
  hc_title(text = "Does it pay to suffer?")
```


```{r}
strava %>% 
  filter(type %in% c("Ride", "Run")) %>% 
  hchart("scatter", hcaes(x = suffer_score, y = average_heartrate, group = type, size = distance)) %>% 
  hc_tooltip(formatter = JS("function(){
                                return (this.point.name + 
                            ' <br> Sport: ' + this.point.type +
                                      ' <br> Average Heart Rate: ' + this.y + 
                                      ' <br> Suffer Score: ' + this.x +
                                      ' <br> Distance: ' + this.point.distance)}")) %>%
  hc_xAxis(title = list(text = "Suffer Score")) %>% 
  hc_yAxis(title = list(text = "Average Heart Rate")) %>%
  hc_add_theme(strava_hc) %>% 
  hc_title(text = "What's a suffer score?")
```

```{r}
strava %>% 
  filter(type %in% c("Ride", "Run")) %>% 
  hchart("scatter", hcaes(x = suffer_score, y = max_heartrate, group = type)) %>% 
  hc_tooltip(formatter = JS("function(){
                                return (this.point.name + 
                            ' <br> Sport: ' + this.point.type +
                                      ' <br> Max Heart Rate: ' + this.y + 
                                      ' <br> Suffer Score: ' + this.x +
                                      ' <br> Distance: ' + this.point.distance)}")) %>%
  hc_xAxis(title = list(text = "Suffer Score")) %>% 
  hc_yAxis(title = list(text = "Maximum Heart Rate")) %>%
  hc_add_theme(strava_hc) %>% 
  hc_title(text = "What's a suffer score?")

```

```{r}
strava %>% 
  filter(type == "Run") %>% 
  hchart("scatter", hcaes(x = distance, y = average_heartrate)) %>% 
  hc_tooltip(formatter = JS("function(){
                                return (this.point.name + 
                            ' <br> Sport: ' + this.point.type +
                                      ' <br> Max Heart Rate: ' + this.y + 
                                      ' <br> Suffer Score: ' + this.x +
                                      ' <br> Distance: ' + this.point.distance)}")) %>%
  hc_xAxis(title = list(text = "Distance (mi)")) %>% 
  hc_yAxis(title = list(text = "Maximum Heart Rate")) %>%
  hc_add_theme(strava_hc) %>% 
  hc_title(text = "")

```

```{r}

strava %>% 
  filter(type %in% c("Ride", "Run")) %>% 
  hchart("scatter", hcaes(x = max_heartrate, y = average_heartrate, group = type, size = distance)) %>% 
  hc_tooltip(formatter = JS("function(){
                                return (this.point.name + 
                            ' <br> Sport: ' + this.point.type +
                                      ' <br> Max Heart Rate: ' + this.y + 
                                      ' <br> Suffer Score: ' + this.x +
                                      ' <br> Distance: ' + this.point.distance)}")) %>%
  hc_xAxis(title = list(text = "Maximum Heart Rate")) %>% 
  hc_yAxis(title = list(text = "Average Heart Rate")) %>%
  hc_add_theme(strava_hc) %>% 
  hc_title(text = "")

```

```{r}
tiles = strava %>% 
  filter(type == "Run" | type == "Ride") %>% 
  filter(date > "2017-12-31")

r2g = c("#D61818", "#FFAE63", "#FFFFBD", "#B5E384")

calendarHeat(tiles$date, tiles$distance, ncolors = 99, color = "r2g", varname="Running & Cycling Miles")
```

```{r}
tiles = strava %>% 
  filter(type == "Run") %>% 
  filter(grepl("2022", date))

# red, orange, yellow, green
r2g = c("#D61818", "#FFAE63", "#FFFFBD", "#B5E384")

calendarHeat(tiles$date, tiles$distance, ncolors = 99, color = "r2g", varname="Running Miles")
```

```{r}
tiles = strava %>% 
  filter(type == "Ride") %>% 
  filter(date > "2017-12-31")

r2g = c("#D61818", "#FFAE63", "#FFFFBD", "#B5E384")

calendarHeat(tiles$date, tiles$distance, ncolors = 99, color = "r2g", varname="Cycling Miles")
```

```{r}
pace = strava %>% 
  filter(type == "Run") %>% 
  mutate(min_per_mile = moving_time / distance)

ggplot(pace, aes(x = date, y = min_per_mile, size = distance)) + 
  geom_point(color = "#c6c6c6", alpha = 0.5) + 
  ylim(6, 15) +
  strava_gg() +
  geom_smooth(color = "#ffffff", fill = "#ffffff") + 
  labs(x = NULL, y = "pace (minutes/mile)")

pace %>% 
  hchart("scatter", hcaes(x = date, y = min_per_mile, size = distance)) %>% 
  hc_tooltip(formatter = JS("function(){
                                return (this.point.name + 
                            ' <br> Sport: ' + this.point.type +
                                      ' <br> Max Heart Rate: ' + this.y + 
                                      ' <br> Suffer Score: ' + this.x +
                                      ' <br> Distance: ' + this.point.distance)}")) %>%
  hc_xAxis(title = list(text = "")) %>% 
  hc_yAxis(title = list(text = "pace (minutes/mile)")) %>%
  hc_add_theme(strava_hc) %>% 
  hc_title(text = "")
```

```{r}
ggplot(pace, aes(x = date, y = average_heartrate, size = distance)) + 
  geom_point(color = "#c6c6c6", alpha = 0.5) + 
  strava_gg() +
  geom_smooth(color = "#ffffff", fill = "#ffffff") +
  labs(x = NULL, y = "average heartrate")
```

## Temporal Aggregations

```{r}
weeks = strava %>% 
  mutate(date = as.Date(start_date_local),
         week = floor_date(date, "week")) %>% 
  group_by(week, type) %>% 
  summarize(miles = sum(distance))

running = weeks %>% 
  filter(type == "Run") %>% 
  ggplot(aes(x = week, y = miles)) + 
  geom_bar(stat = "identity") +
  strava_gg()
running

years = strava %>% 
  mutate(date = as.Date(start_date_local),
         year = year(date)) %>% 
  group_by(year, type) %>% 
  summarize(miles = sum(distance))

years_plot = years %>% 
  filter(type == "Ride" & year > 2017) %>% 
  ggplot(aes(x = year, y = miles, fill = type)) + 
  geom_bar(stat = "identity", position = "dodge", fill = "white") +
  strava_gg() +
  labs(y = "cycling miles", x = NULL)
years_plot

years_run = years %>% 
  filter(type == "Run" & year > 2017) %>% 
  ggplot(aes(x = year, y = miles)) + 
  geom_bar(stat = "identity", fill = "white") +
  strava_gg() +
  labs(y = "running miles", x = NULL)
years_run

running = weeks %>% 
  filter(type == "Run") %>% 
  ggplot(aes(x = week, y = miles)) + 
  geom_bar(stat = "identity", fill = "white") +
  strava_gg()
running

months = strava %>% 
  mutate(date = as.Date(start_date_local),
         month = floor_date(date, "month")) %>%
  group_by(month, type) %>% 
  summarize(miles = sum(distance))

months_run = months %>% 
  filter(type == "Run") %>% 
  ggplot(aes(x = month, y = miles)) + 
  geom_bar(stat = "identity", fill = "white") +
  strava_gg() +
  labs(y = "running miles", x = NULL)
months_run
```

```{r}
cumulative_miles = strava %>% 
  filter(type == "Run") %>% 
  mutate(year = as.factor(year(date)),
         doy = yday(date)) %>% 
  select(year, doy, distance, name) %>% 
  arrange(year, doy) %>% 
  group_by(year) %>% 
  mutate(cumulative_miles = cumsum(distance)) %>% 
  ggplot(aes(x = doy, y = cumulative_miles, color = year)) + 
  geom_point() +
  geom_line() +
  strava_gg()
cumulative_miles

cumulative_miles2 = strava %>% 
  filter(type == "Run") %>% 

  mutate(year = as.factor(year(date)),
         doy = yday(date)) %>% 
    filter(year != "2017") %>% 
  select(year, doy, distance, name) %>% 
  arrange(year, doy) %>% 
  group_by(year) %>% 
  mutate(cumulative_miles = cumsum(distance)) %>% 
  hchart("line", hcaes(x = doy, y = cumulative_miles, group = year), size = 2) %>% 
  hc_tooltip(formatter = JS("function(){
                                return (this.point.name + 
                                      ' <br> Activity distance: ' + this.point.distance +
                            '<br> Year-to-date distance: ' + this.point.cumulative_miles)}")) %>%
  hc_xAxis(title = list(text = "day of year")) %>% 
  hc_yAxis(title = list(text = "year-to-date miles")) %>%
  hc_add_theme(strava_hc) %>% 
  hc_title(text = "")  %>% 
  hc_colors(c("yellow", "#358856", "dodgerblue", "purple", "navy"))
cumulative_miles2
```

## Routes

```{r routes}

# https://www.markhneedham.com/blog/2017/04/29/leaflet-strava-polylines-osm/
# extracting routes form polyline
mini = strava %>% 
  head(10)
```

## Race Training Loads
```{r}
half_training = strava %>% 
  filter(half_marathon == "y") %>% 
  mutate(training_start = date - 90) %>% 
  mutate(race_name = c("Koala 2021", "Aramco 2020 (virtual)", "Aramco 2019", "Koala 2019", "Oilman 2018", "Austin 2017", "Aramco 2017")) %>% 
  #filter(race_name != "Austin 2017") %>% 
  select(race_name, finish_time = moving_time, training_start, race_day = date) 

austin = half_training %>%
  filter(race_name == "Austin 2017") %>% 
  mutate(training_mileage = 244.4) %>% 
  select(training_for = race_name, training_mileage, finish_time, training_start, race_day)
training_periods = strava %>% 
  mutate(training_for = case_when(
    date > "2017-10-16" & date <= "2018-01-14" ~ "Aramco 2017",
    #date > "2017-11-20" & date <= "2018-02-18" ~ "Austin 2017",
    date > "2018-08-06" & date <= "2018-11-04" ~ "Oilman 2018",
    date > "2019-07-29" & date <= "2019-10-27" ~ "Koala 2019",
    date > "2019-10-21" & date <= "2020-01-19" ~ "Aramco 2019",
    date > "2020-10-11" & date <= "2021-01-09" ~ "Aramco 2020 (virtual)",
    date > "2021-07-27" & date <= "2021-10-31" ~ "Koala 2021"
    )) %>% 
  filter(type == "Run") %>% 
  group_by(training_for) %>% 
  summarize(training_mileage = sum(distance)) %>% 
  ungroup() %>% 
  filter(!is.na(training_for)) %>% 
  left_join(half_training, by = c("training_for" = "race_name")) %>% 
  rbind(austin) %>% 
  mutate(finish_time_hr = paste0("2:", str_pad(round(finish_time - 120), 2, pad = "0")))
  
hchart(training_periods, "scatter", hcaes(x = training_mileage, y = finish_time)) %>% 
  hc_tooltip(formatter = JS("function(){
                                return (this.point.training_for + 
                                      ' <br> Finish time: ' + this.point.finish_time_hr +
                            '<br> Training mileage: ' + this.point.training_mileage)}")) %>%
  hc_xAxis(title = list(text = "miles run in the 3 months preceeding the race")) %>% 
  hc_yAxis(title = list(text = "half marathon finish time (minutes)")) %>%
  hc_add_theme(strava_hc) %>% 
  hc_title(text = "") 
```


```{r}
library(ggridges)
ridge = strava %>% 
  filter(type == "Run") %>% 
  mutate(month = as.factor(month(date, label = T, abbr = T)), 
         year = as.factor(year(date))) %>% 
  group_by(year, month) %>% 
  mutate(monthly_miles = sum(distance)) %>% 
  select(month, year, monthly_miles) %>% 
  distinct()

ggplot(ridge, aes(x = monthly_miles, y = month, fill = stat(x))) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_gradient(low = "yellow", high = "red") + 
  #scale_fill_viridis_c(option = "C") +
  labs(x = "MILES", y = "") +
  scale_y_discrete(limits = rev) +
  strava_gg()
ggsave(filename =  here::here("figures", "monthly_ridgeline.jpeg"),
       width = 8, height = 6, units = "in")

ridge_ss = strava %>% 
  filter(type == "Run") %>% 
  mutate(month = as.factor(month(date, label = T, abbr = T)), 
         year = as.factor(year(date))) %>% 
  group_by(year, month) %>% 
  mutate(max_heartrate = mean(max_heartrate, na.rm = T)) %>% 
  select(month, year, max_heartrate) %>% 
  distinct()

ggplot(ridge_ss, aes(x = max_heartrate, y = month, fill = stat(x))) +
  geom_density_ridges_gradient(scale = 3, rel_min_height = 0.01) +
  scale_fill_gradient(low = "yellow", high = "red") + 
  #scale_fill_viridis_c(option = "C") +
  labs(x = "MAX HEART RATE", y = "") +
  scale_y_discrete(limits = rev) +
  strava_gg()
ggsave(filename =  here::here("figures", "monthly_ridgeline.jpeg"),
       width = 8, height = 6, units = "in")
```


```{r}
ridge %>% 
  ggplot(aes(x = month, y = monthly_miles, fill = year)) + 
  geom_bar(stat = "identity", position = "dodge") + 
  theme_bw()

ridge %>% 
  ggplot(aes(x = month, y = monthly_miles, color = year, group = year)) + 
  geom_point() + 
  geom_line() +
  theme_bw()

box = ridge %>% 
  filter(year != "2023") %>% 
  ggplot(aes(x = month, y = monthly_miles)) + 
  geom_boxplot(alpha = 0.7) + 
  strava_gg() +
  theme(legend.position = "top") +
  geom_point(aes(x = month, y = monthly_miles, fill = year), shape = 21, color = "white", size = 3) +
  labs(x = "", y = "MILES", fill = "") +
  scale_fill_manual(values = c("tomato", "yellow", "aquamarine4", "dodgerblue" ,  "purple", "blue")) +
  scale_y_continuous(breaks = seq(0, 150, 25))
box
ggsave(plot = box, filename =  here::here("figures", "monthly_boxplot.jpeg"),
       width = 8, height = 6, units = "in")

```


```{r}
# library(googlePolylines)
# library(leaflet)
# gps = strava %>% 
#   slice(1) #%>% 
#   decode(map.summary_polyline) 
# 
# gps2 = decode(gps)
# 
# leaflet() %>% 
#   addProviderTiles("OpenStreetMap.DE") %>%
#   addPolylines( data = gps2)
  
```

```{r}
# https://www.r-bloggers.com/2018/05/get-your-tracks-from-the-strava-api-and-plot-them-on-leaflet-maps/
options(stringsAsFactors = F)

#rm(list=ls())

library(httr)
library(rjson)
library(leaflet)
library(dplyr)

#token = "c64c112e60d823f191746e72b17cc58ae5df9732 "


# Functions —————————————————————

get.coord.df.from.stream = function (stream.obj) {
  data.frame(lat = sapply(stream.obj[[1]]$data, USE.NAMES = F, FUN = function (x) x[[1]]),
             lon = sapply(stream.obj[[1]]$data, USE.NAMES = F, FUN = function (x) x[[2]]))
}

get.stream.from.activity = function (act.id, token) {
  stream = GET("https://www.strava.com/",
                path = paste0("api/v3/activities/", act.id, "/streams/latlng"),
                query = list(access_token = token))
  content(stream)
}

get.activities2 = function (token) {
  activities = GET("https://www.strava.com/", path = "api/v3/activities",
                    query = list(access_token = token, per_page = 200))
  activities = content(activities, "text")
  activities = fromJSON(activities)
  res.df = data.frame()
  for (a in activities) {
    values = sapply(c("name", "distance", "moving_time", 
                       "elapsed_time", "total_elevation_gain",
                       "type", "id", "start_date_local",
                       "location_country", "average_speed", "max_speed", 
                       "has_heartrate", "elev_high",
                       "elev_low", "average_heartrate", "max_heartrate"), 
                     FUN = function (x) {
                         if (is.null(a[[x]])) {
                           NA } else { a[[x]] }
                       })
    res.df = rbind(res.df, values)
  }
  names(res.df) = c("name", "distance", "moving_time", "elapsed_time", 
                     "total_elevation_gain", "type", "id", "start_date_local",
                     "location_country", "average_speed", "max_speed", 
                     "has_heartrate", "elev_high",
                     "elev_low", "average_heartrate", "max_heartrate")
  res.df
}

get.multiple.streams = function (act.ids, token) {
  res.list = list()
  for (act.id.i in 1:length(act.ids)) {
    if (act.id.i %% 5 == 0) cat("Actitivy no.", act.id.i, "of", length(act.ids), "\n")
    stream = get.stream.from.activity(act.ids[act.id.i], token)
    coord.df = get.coord.df.from.stream(stream)
    res.list[[length(res.list) + 1]] = list(act.id = act.ids[act.id.i],
                                             coords = coord.df)
  }
  res.list
}

activities = get.activities2(token)

stream.list = get.multiple.streams(activities$id, token)

# Leaflet —————————————————————–

lons.range = c(9.156572, 9.237580)
lats.range = c(48.74085, 48.82079)

map = leaflet() %>%
  addProviderTiles("OpenMapSurfer.Grayscale", # nice: CartoDB.Positron, OpenMapSurfer.Grayscale, CartoDB.DarkMatterNoLabels
                   options = providerTileOptions(noWrap = T)) %>%
  fitBounds(lng1 = min(lons.range), lat1 = max(lats.range), lng2 = max(lons.range), lat2 = min(lats.range))

add.run = function (act.id, color, act.name, act.dist, strlist = stream.list) {
  act.ind = sapply(stream.list, USE.NAMES = F, FUN = function (x) {
    x$act.id == act.id
  })
  act.from.list = strlist[act.ind][[1]]
  map <= addPolylines(map, lng = act.from.list$coords$lon,
               lat = act.from.list$coords$lat,
               color = color, opacity = 1/3, weight = 2,
               popup = paste0(act.name, ", ", round(as.numeric(act.dist) / 1000, 2),"km"))
}

# plot all
for (i in 1:nrow(activities)) {
  add.run(activities[i, "id"], ifelse(activities[i, "type"] == "Run", "red",
                                      ifelse(activities[i, "type"] == "Ride", "blue", "black")),
          activities[i, "name"], activities[i, "distance"])
}

map
```

```{r}
# library(ggplot2)
# library(gganimate)
# library(gapminder)
# 
# g = ggplot(gapminder, aes(gdpPercap, lifeExp, size = pop, frame = year)) +
#   geom_point() +
#   geom_smooth(aes(group = year), 
#               method = "lm", 
#               show.legend = FALSE) +
#   facet_wrap(~continent, scales = "free") +
#   scale_x_log10()  # convert to log scale
# 
# gganimate(g, interval=0.2)
# 
# # Create Month Week
# df$yearmonth = as.yearmon(df$date)
# df$yearmonthf = factor(df$yearmonth)
# df = ddply(df,.(yearmonthf), transform, monthweek=1+week-min(week))  # compute week number of month
# df = df[, c("year", "yearmonthf", "monthf", "week", "monthweek", "weekdayf", "VIX.Close")]
# head(df)
# #>   year yearmonthf monthf week monthweek weekdayf VIX.Close
# #> 1 2012   Jan 2012    Jan    1         1      Tue     22.97
# #> 2 2012   Jan 2012    Jan    1         1      Wed     22.22
# #> 3 2012   Jan 2012    Jan    1         1      Thu     21.48
# #> 4 2012   Jan 2012    Jan    1         1      Fri     20.63
# #> 5 2012   Jan 2012    Jan    2         2      Mon     21.07
# #> 6 2012   Jan 2012    Jan    2         2      Tue     20.69
# 
# 
# # Plot
# ggplot(df, aes(monthweek, weekdayf, fill = VIX.Close)) + 
#   geom_tile(colour = "white") + 
#   facet_grid(year~monthf) + 
#   scale_fill_gradient(low="red", high="green") +
#   labs(x="Week of Month",
#        y="",
#        title = "Time-Series Calendar Heatmap", 
#        subtitle="Yahoo Closing Price", 
#        fill="Close")
```

# circular bar chart
```{r}
# https://www.r-graph-gallery.com/299-circular-stacked-barplot.html
 
weeks_run = weeks %>% 
  filter(type == "Run") %>% 
  mutate(year = year(week),
         week_number = week(week),
         month = month(week),
         season = case_when(month %in% c(12, 1, 2) ~ "winter",
                            month %in% c(3, 4, 5) ~ "spring",
                            month %in% c(6, 7, 8) ~ "summer",
                            month %in% c(9, 10, 11) ~ "fall")) %>% 
    filter(year > 2017 & year < 2023) %>% 
  group_by(week_number, year) %>% 
  summarize(weekly_miles = sum(miles, na.rm = T),
            season = season[1])

# prepare a data frame for base lines
base_data = tibble(
  season = c("winter", "spring", "summer", "fall", ""),
  start = c(1, 9, 23, 36, 49),
  end = c(8, 22, 35, 48, 52),
  title = c(3, 15.5, 29, 42, 2)
)

pinwheel = ggplot(weeks_run, aes(x = week_number, y = weekly_miles, fill = forcats::fct_rev(as.factor(year)))) + 
  geom_bar(position = "stack", stat = "identity", color = "white", size = 0.5) +

  coord_polar() +
  theme(legend.position = "none") +
  #ylim(-30,125) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm") 
  ) +
  scale_fill_manual(values = c("dodgerblue", "aquamarine4", "yellow", "tomato", "blue")) +
  # Add base line information
  geom_segment(data = base_data, 
               aes(x = start, y = -3, xend = end, yend = -3), colour = "black", size = 0.6, inherit.aes = F) +
  geom_text(data = base_data, 
            aes(x = title, y = -8, label = season), 
            hjust = c(1, 1, 0, 0, 0), colour = "black", size = 3, inherit.aes = F)
pinwheel
ggsave(pinwheel, file = here::here("figures", "pinwheel.jpg"), width = 10, height = 10)

months_run = months %>% 
  filter(type == "Run") %>% 
  mutate(year = year(month),
         month_name = month(month, label = T, abbr = T)) %>% 
    filter(year > 2017 & year < 2023) %>% 
  group_by(month_name, year) %>% 
  summarize(monthly_miles = sum(miles, na.rm = T))

pinwheel_month = ggplot(months_run, aes(x = month_name, y = monthly_miles, fill = forcats::fct_rev(as.factor(year)))) + 
  geom_bar(position = "stack", stat = "identity", color = "white", size = 0.5) +
  coord_polar() +
  theme(legend.position = "none") +
  ylim(-30,700) +
  theme_minimal() +
  theme(
    legend.position = "none",
    axis.text = element_blank(),
    axis.title = element_blank(),
    panel.grid = element_blank(),
    plot.margin = unit(rep(-1,4), "cm") 
  ) +
  scale_fill_manual(values = c("dodgerblue", "aquamarine4", "yellow", "tomato", "blue"))
pinwheel_month
```
```{r}
bars_month = ggplot(months_run, aes(x = month_name, y = monthly_miles, fill = forcats::fct_rev(as.factor(year)))) + 
  geom_bar(position = "stack", stat = "identity", color = "white", size = 0.5) +
  strava_gg() +
  scale_fill_manual(values = c("dodgerblue", "aquamarine4", "yellow", "tomato", "blue")) +
  labs(x = NULL, y = "miles") +
  theme(legend.position = "top",
        legend.title = element_blank())
bars_month
```


```{r}
hchart(weeks_run, "column", hcaes(x = week_number, y = weekly_miles, group = forcats::fct_rev(as.factor(year)))) %>% 
  hc_chart(polar = T) %>% 
  hc_add_theme(strava_hc) %>% 
  hc_colors(c("dodgerblue", "white", "yellow", "#358856")) %>% 
  hc_plotOptions(column = list(stacking = "normal"),
                           series = list(showInLegend = T)) %>% 
  #hc_yAxis(min = 10, max = 110, title = "") %>% 
  hc_xAxis(title = "") %>% 
  hc_tooltip(formatter = JS("function(){
                                return ('Week ' + this.point.week_number + ', ' + this.point.year +
                            '<br> Miles Run: ' + this.point.weekly_miles)}"))
```

